on: [workflow_dispatch]

jobs:
  custom-js-action-job:
    
    runs-on:ubuntu-latest
    
    name: Custom JS Github Action
    
    
    steps:
      -name: First Custom GitHub Actions
       id: mjsids
       uses: Meiyanthan/custom-action-simple@v1.1
       
       with:
        name-of-user: 'Welcome Manikandan!!!'
        
      -name: Output of Timestamp
       run: echo "The time was ${{step.mjsids.outputs.time}}"
