on: [workflow_dispatch]

jobs:
    custom-js-action-job:
        name: "Custom JS Github Action"
        runs-on: ubuntu-latest
        steps:
        
          - name: "First Custom GitHub Action"
            id: mjsids
            uses: Meiyanthan/custom-action-simple@v1.1
     
            with:
                name-of-user: 'Welcome Manikandan!!!'
   
        
          - name: Output of Timestamp
            run: echo "The time was ${{steps.mjsids.outputs.time}}"
